apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: webapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
      - name: webapplication
        image: 707677861059.dkr.ecr.ap-northeast-2.amazonaws.com/nadeuri:b714b0a9a414fddfcd539b50c39fa733fe56585c
        ports:
        - containerPort: 8080