apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: webapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
      - name: webapplication
        image: 707677861059.dkr.ecr.ap-northeast-2.amazonaws.com/nadeuri:2c28e419adceb13c898684f402e55be7bbcec676
        ports:
        - containerPort: 8080
        env:
        - name: RDS_HOST
          value: rds-service
